<a href="https://colab.research.google.com/github/Anusha3104/AI_ML_intership/blob/main/pandaslib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [8]:
#series Definition:Creates a 1-dimensional labeled array.


n = pd.Series([1,2,3,4,5,6,7,8])
print(n)

n1 = pd.Series([1,2,3,4],index=['a','b','c','d'])
print(n1)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64

In [11]:
# Dataframe :Creates a 2-dimensional table (rows and columns).
data = {
    "Name": ['A', 'B'],
    "Age": [12,14]
}
d = pd.DataFrame(data)
print(d)

  Name  Age
0    A   12
1    B   14

In [13]:
df = pd.read_csv("winequality.csv")

In [15]:
#df.head() = shows the first 5 rows
df.head()
df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,5
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5,6
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7,8
9,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,9.2,5,10

In [16]:
#df.tail() it shows last 5 rows
df.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [17]:
df.shape

(1143, 13)

In [18]:
#df.columns : retrun all column names
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id'],
      dtype='object')

In [19]:
#df.index returns row index
df.index

RangeIndex(start=0, stop=1143, step=1)

In [20]:
#df.info() Gives information about the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [21]:
#df.describe(): Shows statistical summary of numerical columns.
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [22]:
#df["column"]: access any column
df["pH"]

0       3.51
1       3.20
2       3.26
3       3.16
4       3.51
        ...
1138    3.42
1139    3.42
1140    3.45
1141    3.52
1142    3.57
Name: pH, Length: 1143, dtype: float64

In [23]:
#df.iloc[]: Accesses rows and columns using index positions.
df.iloc[0]

fixed acidity            7.4000
volatile acidity         0.7000
citric acid              0.0000
residual sugar           1.9000
chlorides                0.0760
free sulfur dioxide     11.0000
total sulfur dioxide    34.0000
density                  0.9978
pH                       3.5100
sulphates                0.5600
alcohol                  9.4000
quality                  5.0000
Id                       0.0000
Name: 0, dtype: float64

In [33]:
df.iloc[0,5]

np.float64(11.0)

In [36]:
#df.loc[]: Accesses rows and columns using labels (names).
df.loc[:,["citric acid","pH"]]

      citric acid    pH
0            0.00  3.51
1            0.00  3.20
2            0.04  3.26
3            0.56  3.16
4            0.00  3.51
...           ...   ...
1138         0.13  3.42
1139         0.08  3.42
1140         0.08  3.45
1141         0.10  3.52
1142         0.12  3.57

[1143 rows x 2 columns]

In [38]:
df["citric acid"].unique()

array([0.  , 0.04, 0.56, 0.06, 0.02, 0.08, 0.29, 0.51, 0.31, 0.21, 0.11,
       0.14, 0.16, 0.24, 0.07, 0.12, 0.25, 0.28, 0.36, 0.3 , 0.2 , 0.22,
       0.15, 0.43, 0.26, 0.57, 0.18, 0.4 , 0.49, 0.05, 0.64, 0.47, 0.48,
       0.44, 0.68, 0.19, 0.09, 0.17, 0.55, 0.1 , 1.  , 0.03, 0.42, 0.33,
       0.35, 0.6 , 0.74, 0.37, 0.5 , 0.23, 0.76, 0.46, 0.45, 0.32, 0.53,
       0.52, 0.39, 0.66, 0.62, 0.01, 0.54, 0.67, 0.79, 0.63, 0.61, 0.59,
       0.34, 0.73, 0.72, 0.69, 0.65, 0.41, 0.75, 0.58, 0.13, 0.27, 0.38])

In [39]:
# value_counts: Counts frequency of each value.
df.value_counts("pH")

pH
3.30    41
3.36    40
3.38    38
3.39    37
3.26    33
        ..
3.63     1
3.74     1
3.71     1
3.70     1
3.75     1
Name: count, Length: 87, dtype: int64

In [41]:
df.isnull()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,False,False,False,False,False,False,False,False,False,False,False,False,False
1139,False,False,False,False,False,False,False,False,False,False,False,False,False
1140,False,False,False,False,False,False,False,False,False,False,False,False,False
1141,False,False,False,False,False,False,False,False,False,False,False,False,False
1142,False,False,False,False,False,False,False,False,False,False,False,False,False

In [42]:
df.sort_values("citric acid", ascending= False)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
103,9.2,0.520,1.00,3.4,0.610,32.0,69.0,0.9996,2.74,2.00,9.4,4,151
248,13.5,0.530,0.79,4.8,0.120,23.0,77.0,1.0018,3.18,0.77,13.0,5,353
311,15.6,0.685,0.76,3.7,0.100,6.0,43.0,1.0032,2.95,0.68,11.2,7,442
182,7.7,0.410,0.76,1.8,0.611,8.0,45.0,0.9968,3.06,1.26,9.4,5,258
274,12.0,0.370,0.76,4.2,0.066,7.0,38.0,1.0004,3.22,0.60,13.0,7,395
...,...,...,...,...,...,...,...,...,...,...,...,...,...
798,9.1,0.600,0.00,1.9,0.058,5.0,10.0,0.9977,3.18,0.63,10.4,6,1130
526,8.2,0.590,0.00,2.5,0.093,19.0,58.0,1.0002,3.50,0.65,9.3,6,737
7,7.3,0.650,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7,7
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [44]:
#groupby: groups data based on a column
df["citric acid"].mean()

np.float64(0.2683639545056868)

In [46]:
df.to_csv("output.csv")#Saves DataFrame into a CSV file.